apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abirelhajahmed/backend:18
          ports:
            - containerPort: 3700
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
          resources:  
            requests:
              memory: "256Mi"  
              cpu: "200m"      
            limits:
              memory: "512Mi"  
              cpu: "500m"
