apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
<<<<<<< HEAD
        image: abirelhajahmed/frontend:39
=======
        image: abirelhajahmed/frontend:39
>>>>>>> da3e324435748d42f487bed37ca22f785032467b
        ports:
        - containerPort: 3000
